version: '3.7'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx-server
    depends_on:
      - wordpress
    container_name: nginx-server
    ports:
      - 443:443
    networks:
      - inception-network
    volumes:
      - wp-data:/var/www/html/
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb-database
    networks:
      - inception-network
    volumes:
      - db-data:/var/lib/mysql/
    env_file:
      - .env
    restart: on-failure

volumes:
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type: none
      device: /home/joao-per/data/wordpress
      o: bind
  mariadb_data:
    name: mariadb_data
    driver_opts:
      type: none
      device: /home/joao-per/data/mysql
      o: bind

networks:
  inception-network:
    name: inception
