version: '3'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    links:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
    links:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  wordpress_data:
  mariadb_data:
