version: '3'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=joaoper
      - WORDPRESS_DB_PASSWORD=macaco
      - WORDPRESS_DB_NAME=inception

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=coxinha
      - MYSQL_DATABASE=inception
      - MYSQL_USER=joaoper
      - MYSQL_PASSWORD=macaco

volumes:
  wordpress_data:
  mariadb_data:

networks:
  default:
    external:
      name: inception
