version: '3.7'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    depends_on:
      - wordpress
    container_name: nginx
    ports:
      - 443:443
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html/
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception-network
    ports:
      - 9000
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    networks:
      - inception-network
    volumes:
      - mariadb_data:/var/lib/mysql/
    env_file:
      - .env
    restart: on-failure

volumes:
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type: none
      device: /mnt/c/Users/jonat/data/wordpress
      o: bind
  mariadb_data:
    name: mariadb_data
    driver_opts:
      type: none
      device: /mnt/c/Users/jonat/data/mysql
      o: bind

networks:
  inception-network:
    name: inception
